// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file adksim/v1/simulator_service.proto (package adksim.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from '@bufbuild/protobuf/codegenv2';
import { fileDesc, messageDesc, serviceDesc } from '@bufbuild/protobuf/codegenv2';
import type { SessionEvent, SimulatorSession } from './simulator_session_pb';
import { file_adksim_v1_simulator_session } from './simulator_session_pb';
import type {
  GenerateContentRequest,
  GenerateContentResponse,
} from '../../google/ai/generativelanguage/v1beta/generative_service_pb';
import { file_google_ai_generativelanguage_v1beta_generative_service } from '../../google/ai/generativelanguage/v1beta/generative_service_pb';
import type { Message } from '@bufbuild/protobuf';

/**
 * Describes the file adksim/v1/simulator_service.proto.
 */
export const file_adksim_v1_simulator_service: GenFile =
  /*@__PURE__*/
  fileDesc(
    'CiFhZGtzaW0vdjEvc2ltdWxhdG9yX3NlcnZpY2UucHJvdG8SCWFka3NpbS52MSIrChRDcmVhdGVTZXNzaW9uUmVxdWVzdBITCgtkZXNjcmlwdGlvbhgBIAEoCSJFChVDcmVhdGVTZXNzaW9uUmVzcG9uc2USLAoHc2Vzc2lvbhgBIAEoCzIbLmFka3NpbS52MS5TaW11bGF0b3JTZXNzaW9uIjkKEFN1YnNjcmliZVJlcXVlc3QSEgoKc2Vzc2lvbl9pZBgBIAEoCRIRCgljbGllbnRfaWQYAiABKAkiOwoRU3Vic2NyaWJlUmVzcG9uc2USJgoFZXZlbnQYASABKAsyFy5hZGtzaW0udjEuU2Vzc2lvbkV2ZW50Ip0BChRTdWJtaXRSZXF1ZXN0UmVxdWVzdBISCgpzZXNzaW9uX2lkGAEgASgJEg8KB3R1cm5faWQYAiABKAkSEgoKYWdlbnRfbmFtZRgDIAEoCRJMCgdyZXF1ZXN0GAQgASgLMjsuZ29vZ2xlLmFpLmdlbmVyYXRpdmVsYW5ndWFnZS52MWJldGEuR2VuZXJhdGVDb250ZW50UmVxdWVzdCIpChVTdWJtaXRSZXF1ZXN0UmVzcG9uc2USEAoIZXZlbnRfaWQYASABKAkijAEKFVN1Ym1pdERlY2lzaW9uUmVxdWVzdBISCgpzZXNzaW9uX2lkGAEgASgJEg8KB3R1cm5faWQYAiABKAkSTgoIcmVzcG9uc2UYAyABKAsyPC5nb29nbGUuYWkuZ2VuZXJhdGl2ZWxhbmd1YWdlLnYxYmV0YS5HZW5lcmF0ZUNvbnRlbnRSZXNwb25zZSIqChZTdWJtaXREZWNpc2lvblJlc3BvbnNlEhAKCGV2ZW50X2lkGAEgASgJIjwKE0xpc3RTZXNzaW9uc1JlcXVlc3QSEQoJcGFnZV9zaXplGAEgASgFEhIKCnBhZ2VfdG9rZW4YAiABKAkiXgoUTGlzdFNlc3Npb25zUmVzcG9uc2USLQoIc2Vzc2lvbnMYASADKAsyGy5hZGtzaW0udjEuU2ltdWxhdG9yU2Vzc2lvbhIXCg9uZXh0X3BhZ2VfdG9rZW4YAiABKAkyrAMKEFNpbXVsYXRvclNlcnZpY2USUgoNQ3JlYXRlU2Vzc2lvbhIfLmFka3NpbS52MS5DcmVhdGVTZXNzaW9uUmVxdWVzdBogLmFka3NpbS52MS5DcmVhdGVTZXNzaW9uUmVzcG9uc2USSAoJU3Vic2NyaWJlEhsuYWRrc2ltLnYxLlN1YnNjcmliZVJlcXVlc3QaHC5hZGtzaW0udjEuU3Vic2NyaWJlUmVzcG9uc2UwARJSCg1TdWJtaXRSZXF1ZXN0Eh8uYWRrc2ltLnYxLlN1Ym1pdFJlcXVlc3RSZXF1ZXN0GiAuYWRrc2ltLnYxLlN1Ym1pdFJlcXVlc3RSZXNwb25zZRJVCg5TdWJtaXREZWNpc2lvbhIgLmFka3NpbS52MS5TdWJtaXREZWNpc2lvblJlcXVlc3QaIS5hZGtzaW0udjEuU3VibWl0RGVjaXNpb25SZXNwb25zZRJPCgxMaXN0U2Vzc2lvbnMSHi5hZGtzaW0udjEuTGlzdFNlc3Npb25zUmVxdWVzdBofLmFka3NpbS52MS5MaXN0U2Vzc2lvbnNSZXNwb25zZWIGcHJvdG8z',
    [file_adksim_v1_simulator_session, file_google_ai_generativelanguage_v1beta_generative_service],
  );

/**
 * CreateSessionRequest is sent by the Plugin to register a new session.
 *
 * @generated from message adksim.v1.CreateSessionRequest
 */
export type CreateSessionRequest = Message<'adksim.v1.CreateSessionRequest'> & {
  /**
   * Optional description for the session.
   *
   * @generated from field: string description = 1;
   */
  description: string;
};

/**
 * Describes the message adksim.v1.CreateSessionRequest.
 * Use `create(CreateSessionRequestSchema)` to create a new message.
 */
export const CreateSessionRequestSchema: GenMessage<CreateSessionRequest> =
  /*@__PURE__*/
  messageDesc(file_adksim_v1_simulator_service, 0);

/**
 * CreateSessionResponse contains the created or existing session.
 *
 * @generated from message adksim.v1.CreateSessionResponse
 */
export type CreateSessionResponse = Message<'adksim.v1.CreateSessionResponse'> & {
  /**
   * The session that was created or retrieved.
   *
   * @generated from field: adksim.v1.SimulatorSession session = 1;
   */
  session?: SimulatorSession;
};

/**
 * Describes the message adksim.v1.CreateSessionResponse.
 * Use `create(CreateSessionResponseSchema)` to create a new message.
 */
export const CreateSessionResponseSchema: GenMessage<CreateSessionResponse> =
  /*@__PURE__*/
  messageDesc(file_adksim_v1_simulator_service, 1);

/**
 * SubscribeRequest initiates an event stream subscription.
 *
 * @generated from message adksim.v1.SubscribeRequest
 */
export type SubscribeRequest = Message<'adksim.v1.SubscribeRequest'> & {
  /**
   * The session ID to subscribe to.
   *
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * Client identifier for debug/logging purposes (UUID).
   *
   * @generated from field: string client_id = 2;
   */
  clientId: string;
};

/**
 * Describes the message adksim.v1.SubscribeRequest.
 * Use `create(SubscribeRequestSchema)` to create a new message.
 */
export const SubscribeRequestSchema: GenMessage<SubscribeRequest> =
  /*@__PURE__*/
  messageDesc(file_adksim_v1_simulator_service, 2);

/**
 * SubscribeResponse wraps a SessionEvent in the subscription stream.
 *
 * @generated from message adksim.v1.SubscribeResponse
 */
export type SubscribeResponse = Message<'adksim.v1.SubscribeResponse'> & {
  /**
   * The event being streamed.
   *
   * @generated from field: adksim.v1.SessionEvent event = 1;
   */
  event?: SessionEvent;
};

/**
 * Describes the message adksim.v1.SubscribeResponse.
 * Use `create(SubscribeResponseSchema)` to create a new message.
 */
export const SubscribeResponseSchema: GenMessage<SubscribeResponse> =
  /*@__PURE__*/
  messageDesc(file_adksim_v1_simulator_service, 3);

/**
 * SubmitRequestRequest publishes an intercepted LLM request.
 *
 * @generated from message adksim.v1.SubmitRequestRequest
 */
export type SubmitRequestRequest = Message<'adksim.v1.SubmitRequestRequest'> & {
  /**
   * The session to publish to.
   *
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * Correlation ID for this request/response pair.
   *
   * @generated from field: string turn_id = 2;
   */
  turnId: string;

  /**
   * Name of the agent making the request.
   *
   * @generated from field: string agent_name = 3;
   */
  agentName: string;

  /**
   * The intercepted LLM request.
   *
   * @generated from field: google.ai.generativelanguage.v1beta.GenerateContentRequest request = 4;
   */
  request?: GenerateContentRequest;
};

/**
 * Describes the message adksim.v1.SubmitRequestRequest.
 * Use `create(SubmitRequestRequestSchema)` to create a new message.
 */
export const SubmitRequestRequestSchema: GenMessage<SubmitRequestRequest> =
  /*@__PURE__*/
  messageDesc(file_adksim_v1_simulator_service, 4);

/**
 * SubmitRequestResponse confirms the request was received.
 *
 * @generated from message adksim.v1.SubmitRequestResponse
 */
export type SubmitRequestResponse = Message<'adksim.v1.SubmitRequestResponse'> & {
  /**
   * The event ID assigned to this request.
   *
   * @generated from field: string event_id = 1;
   */
  eventId: string;
};

/**
 * Describes the message adksim.v1.SubmitRequestResponse.
 * Use `create(SubmitRequestResponseSchema)` to create a new message.
 */
export const SubmitRequestResponseSchema: GenMessage<SubmitRequestResponse> =
  /*@__PURE__*/
  messageDesc(file_adksim_v1_simulator_service, 5);

/**
 * SubmitDecisionRequest publishes a human decision.
 *
 * @generated from message adksim.v1.SubmitDecisionRequest
 */
export type SubmitDecisionRequest = Message<'adksim.v1.SubmitDecisionRequest'> & {
  /**
   * The session this decision belongs to.
   *
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * Correlation ID linking to the original request.
   *
   * @generated from field: string turn_id = 2;
   */
  turnId: string;

  /**
   * The human's response.
   *
   * @generated from field: google.ai.generativelanguage.v1beta.GenerateContentResponse response = 3;
   */
  response?: GenerateContentResponse;
};

/**
 * Describes the message adksim.v1.SubmitDecisionRequest.
 * Use `create(SubmitDecisionRequestSchema)` to create a new message.
 */
export const SubmitDecisionRequestSchema: GenMessage<SubmitDecisionRequest> =
  /*@__PURE__*/
  messageDesc(file_adksim_v1_simulator_service, 6);

/**
 * SubmitDecisionResponse confirms the decision was received.
 *
 * @generated from message adksim.v1.SubmitDecisionResponse
 */
export type SubmitDecisionResponse = Message<'adksim.v1.SubmitDecisionResponse'> & {
  /**
   * The event ID assigned to this decision.
   *
   * @generated from field: string event_id = 1;
   */
  eventId: string;
};

/**
 * Describes the message adksim.v1.SubmitDecisionResponse.
 * Use `create(SubmitDecisionResponseSchema)` to create a new message.
 */
export const SubmitDecisionResponseSchema: GenMessage<SubmitDecisionResponse> =
  /*@__PURE__*/
  messageDesc(file_adksim_v1_simulator_service, 7);

/**
 * ListSessionsRequest queries for historical sessions.
 *
 * @generated from message adksim.v1.ListSessionsRequest
 */
export type ListSessionsRequest = Message<'adksim.v1.ListSessionsRequest'> & {
  /**
   * Maximum number of sessions to return.
   *
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * Pagination token from a previous response.
   *
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message adksim.v1.ListSessionsRequest.
 * Use `create(ListSessionsRequestSchema)` to create a new message.
 */
export const ListSessionsRequestSchema: GenMessage<ListSessionsRequest> =
  /*@__PURE__*/
  messageDesc(file_adksim_v1_simulator_service, 8);

/**
 * ListSessionsResponse contains the requested sessions.
 *
 * @generated from message adksim.v1.ListSessionsResponse
 */
export type ListSessionsResponse = Message<'adksim.v1.ListSessionsResponse'> & {
  /**
   * The sessions matching the query.
   *
   * @generated from field: repeated adksim.v1.SimulatorSession sessions = 1;
   */
  sessions: SimulatorSession[];

  /**
   * Token for fetching the next page, if any.
   *
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message adksim.v1.ListSessionsResponse.
 * Use `create(ListSessionsResponseSchema)` to create a new message.
 */
export const ListSessionsResponseSchema: GenMessage<ListSessionsResponse> =
  /*@__PURE__*/
  messageDesc(file_adksim_v1_simulator_service, 9);

/**
 * SimulatorService provides the "Remote Brain" protocol for the ADK Agent Simulator.
 * It enables human-in-the-loop validation of agent workflows by intercepting LLM calls
 * and routing them to a web UI for manual decision-making.
 *
 * @generated from service adksim.v1.SimulatorService
 */
export const SimulatorService: GenService<{
  /**
   * CreateSession registers a new simulation session (or ensures existence).
   * Called by the Plugin when an ADK application starts.
   *
   * @generated from rpc adksim.v1.SimulatorService.CreateSession
   */
  createSession: {
    methodKind: 'unary';
    input: typeof CreateSessionRequestSchema;
    output: typeof CreateSessionResponseSchema;
  };
  /**
   * Subscribe opens a bidirectional event stream for a session.
   * Server MUST replay all historical events before streaming live ones.
   * Used by both Plugin and UI to receive real-time updates.
   *
   * @generated from rpc adksim.v1.SimulatorService.Subscribe
   */
  subscribe: {
    methodKind: 'server_streaming';
    input: typeof SubscribeRequestSchema;
    output: typeof SubscribeResponseSchema;
  };
  /**
   * SubmitRequest publishes an intercepted LLM request to the session.
   * Called by the Plugin when an agent triggers a model call.
   *
   * @generated from rpc adksim.v1.SimulatorService.SubmitRequest
   */
  submitRequest: {
    methodKind: 'unary';
    input: typeof SubmitRequestRequestSchema;
    output: typeof SubmitRequestResponseSchema;
  };
  /**
   * SubmitDecision publishes a human decision (response) to the session.
   * Called by the UI when the user completes their response.
   *
   * @generated from rpc adksim.v1.SimulatorService.SubmitDecision
   */
  submitDecision: {
    methodKind: 'unary';
    input: typeof SubmitDecisionRequestSchema;
    output: typeof SubmitDecisionResponseSchema;
  };
  /**
   * ListSessions returns all historical sessions for the landing page.
   *
   * @generated from rpc adksim.v1.SimulatorService.ListSessions
   */
  listSessions: {
    methodKind: 'unary';
    input: typeof ListSessionsRequestSchema;
    output: typeof ListSessionsResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_adksim_v1_simulator_service, 0);
