#!/usr/bin/env bash
# scripts/configure_github.sh
# -----------------------------------------------------------------------------
# PURPOSE: Configures GitHub Native Security features for adk-sim-plugin.
# PREREQUISITES:
#   1. GitHub CLI installed (gh)
#   2. Authenticated with admin access (gh auth login)
#   3. Run from the repository root
# -----------------------------------------------------------------------------

set -euo pipefail

# Configuration
REPO_OWNER="kevinaud"
REPO_NAME="adk-sim-plugin"
FULL_REPO="$REPO_OWNER/$REPO_NAME"

echo "🔒 Configuring GitHub Security for: $FULL_REPO"

# -----------------------------------------------------------------------------
# 1. Repository API Settings (The "Switches")
# -----------------------------------------------------------------------------
# We use the GitHub API to flip the switches that don't have config files.
# - secret_scanning: Scans history for leaked keys.
# - secret_scanning_push_protection: Rejects pushes containing keys.
# - private_vulnerability_reporting: Allows researchers to report bugs privately.
# -----------------------------------------------------------------------------

echo "   -> Enforcing Repository Security Settings via API..."

gh api --method PATCH "repos/$FULL_REPO" \
  --header "X-GitHub-Api-Version: 2022-11-28" \
  --field security_and_analysis[secret_scanning][status]="enabled" \
  --field security_and_analysis[secret_scanning_push_protection][status]="enabled" \
  --field enable_private_vulnerability_reporting=true \
  --silent

echo "      [✓] Secret Scanning Enabled"
echo "      [✓] Push Protection Enabled"
echo "      [✓] Private Vulnerability Reporting Enabled"

# -----------------------------------------------------------------------------
# 2. Dependency Management (Dependabot)
# -----------------------------------------------------------------------------
# Creates a .github/dependabot.yml tailored to your monorepo structure.
# We explicitly map the different sub-projects (frontend, server, plugins).
# -----------------------------------------------------------------------------

echo "   -> Generating .github/dependabot.yml..."
mkdir -p .github

cat <<EOF > .github/dependabot.yml
# Generated by scripts/configure_github.sh
version: 2
updates:
  # 1. Maintain GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # 2. Frontend (Angular)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # 3. Backend Server (Python)
  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "weekly"
    # Note: Dependabot will parse pyproject.toml

  # 4. Plugins (Python)
  - package-ecosystem: "pip"
    directory: "/plugins/python"
    schedule:
      interval: "weekly"

  # 5. Docker Configurations
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
EOF

echo "      [✓] File created."

# -----------------------------------------------------------------------------
# 3. Static Analysis (CodeQL)
# -----------------------------------------------------------------------------
# Creates a CodeQL workflow that scans both Python (Backend) and
# Javascript/Typescript (Frontend).
# -----------------------------------------------------------------------------

echo "   -> Generating .github/workflows/codeql.yml..."
mkdir -p .github/workflows

cat <<EOF > .github/workflows/codeql.yml
# Generated by scripts/configure_github.sh
name: "CodeQL Security Scan"

on:
  push:
    branches: [ "main" ]
  pull_request:
    # Scan all PRs targeting main
    branches: [ "main" ]
  schedule:
    # Weekly full scan (Sunday at 00:00 UTC)
    - cron: '0 0 * * 0'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        # Scan both your backend (python) and frontend (javascript-typescript)
        language: [ 'python', 'javascript-typescript' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: \${{ matrix.language }}
          # Optimization: Exclude docs and test fixtures to speed up scanning
          config: |
            paths-ignore:
              - 'docs/**'
              - '**/tests/**'
              - '**/test_*.py'

      # Auto-build attempts to build compiled languages.
      # For Python/JS it basically just prepares the environment.
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:\${{ matrix.language }}"
EOF

echo "      [✓] File created."

echo "-----------------------------------------------------------------------"
echo "✅ Configuration Complete!"
echo "   1. API settings enforced."
echo "   2. Config files generated."
echo ""
echo "NEXT STEPS:"
echo "   git add .github/dependabot.yml .github/workflows/codeql.yml"
echo "   git commit -m 'chore: configure github security infrastructure'"
echo "   git push"
echo "-----------------------------------------------------------------------"
