#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

cd "$REPO_ROOT"

echo "🔧 Generating code from proto files..."

# Clean output directories
echo "🧹 Cleaning output directories..."
rm -rf "$REPO_ROOT/packages/adk-sim-protos/src/adk_sim_protos/adksim"
rm -rf "$REPO_ROOT/packages/adk-sim-protos/src/adk_sim_protos/google"
rm -rf "$REPO_ROOT/packages/adk-sim-protos-ts/src/adksim"
rm -rf "$REPO_ROOT/packages/adk-sim-protos-ts/src/google"

# Generate code using buf (configured in buf.yaml)
echo "📦 Running buf generate..."
PATH="$REPO_ROOT/.venv/bin:$PATH" buf generate

# Format Python generated code with ruff
echo "🎨 Formatting Python generated code..."
uv run ruff check --fix "$REPO_ROOT/packages/adk-sim-protos/src/adk_sim_protos" 2>/dev/null || true
uv run ruff format "$REPO_ROOT/packages/adk-sim-protos/src/adk_sim_protos"

# Format TypeScript generated code with prettier
echo "🎨 Formatting TypeScript generated code..."
cd "$REPO_ROOT/frontend"
npx prettier --write "../packages/adk-sim-protos-ts/src/**/*.ts" 2>/dev/null || true

# Generate custom index.ts with convenient re-exports
echo "📝 Generating custom index.ts for @adk-sim/protos..."
cat > "$REPO_ROOT/packages/adk-sim-protos-ts/src/index.ts" << 'EOF'
// ADK Simulator Protocol Buffers - TypeScript
// This file is auto-generated by scripts/gen_protos.sh - do not edit manually

// ADK Simulator types
export * from './adksim/v1/simulator_service_pb.js';
export * from './adksim/v1/simulator_session_pb.js';

// Re-export Content types for converters
export type {
  Content,
  Part,
  FunctionCall,
  FunctionResponse,
  Blob,
  Tool,
  FunctionDeclaration,
  Schema,
  ToolConfig,
} from './google/ai/generativelanguage/v1beta/content_pb.js';

export {
  ContentSchema,
  PartSchema,
  FunctionCallSchema,
  FunctionResponseSchema,
  BlobSchema,
  ToolSchema,
  FunctionDeclarationSchema,
  SchemaSchema,
  ToolConfigSchema,
  Type,
} from './google/ai/generativelanguage/v1beta/content_pb.js';

// Re-export GenerativeService types
export type {
  GenerateContentRequest,
  GenerateContentResponse,
  GenerationConfig,
  Candidate,
} from './google/ai/generativelanguage/v1beta/generative_service_pb.js';

export {
  GenerateContentRequestSchema,
  GenerateContentResponseSchema,
  GenerationConfigSchema,
  CandidateSchema,
  Candidate_FinishReason,
} from './google/ai/generativelanguage/v1beta/generative_service_pb.js';

// Re-export Safety types
export type {
  SafetySetting,
  SafetyRating,
} from './google/ai/generativelanguage/v1beta/safety_pb.js';

export {
  SafetySettingSchema,
  SafetyRatingSchema,
  HarmCategory,
  SafetySetting_HarmBlockThreshold,
} from './google/ai/generativelanguage/v1beta/safety_pb.js';
EOF

echo "✅ Proto generation complete!"
echo "📦 Python package: adk_sim_protos.adksim.v1"
echo "📦 TypeScript: packages/adk-sim-protos-ts/src/adksim/v1/"
